#!/bin/bash
# PAI Hook: PAI-Init
# Event: agentSpawn
# Description: Initialize PAI context on agent spawn
# Generated by PAI-Kiro adapter

# PAI AgentSpawn hook: PAI-Init
HOOK_EVENT=$1
INPUT=$(cat)

# Output PAI context to STDOUT (added to agent context by Kiro CLI)
cat << 'PAIEOF'
=== PAI Context ===
PAI v5.0.0 running on Kiro CLI v2.2.2
Algorithm: v6.3.0 (OBSERVE → THINK → PLAN → BUILD → EXECUTE → VERIFY → LEARN)
Memory: ~/.kiro/pai/MEMORY/
Skills: ~/.kiro/skills/

Core Capabilities:
- 45+ specialized skills
- 7-phase Algorithm loop
- TELOS goal system
- Persistent memory
- Platform-agnostic architecture
PAIEOF

exit 0
