#!/bin/bash
# PAI Hook: PromptProcessing
# Event: userPromptSubmit
# Description: Mode classifier for Algorithm (MINIMAL/NATIVE/ALGORITHM)
# Generated by PAI-Kiro adapter

# PAI UserPromptSubmit hook: PromptProcessing
INPUT=$(cat)

# Classify prompt mode based on complexity
# Modes: MINIMAL (<90s), NATIVE (90s-5min), ALGORITHM (>5min)

PROMPT=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('prompt',''))" 2>/dev/null)

if [ -n "$PROMPT" ]; then
  PROMPT_LEN=$(echo "$PROMPT" | wc -c)
  if [ "$PROMPT_LEN" -lt 100 ]; then
    echo "Mode: MINIMAL (quick task)"
  elif [ "$PROMPT_LEN" -lt 500 ]; then
    echo "Mode: NATIVE (standard task)"
  else
    echo "Mode: ALGORITHM (complex task - use 7-phase loop)"
  fi
fi

exit 0
