#!/bin/bash
# PAI Hook: WorkCompletionLearning
# Event: stop
# Description: Capture learnings when agent stops
# Generated by PAI-Kiro adapter

# PAI Stop hook: WorkCompletionLearning
INPUT=$(cat)

# Capture session learnings
SESSION_ID=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('session_id','unknown'))" 2>/dev/null)

echo "[PAI] Session $SESSION_ID completed" >&2

exit 0
