#!/bin/bash
# PAI Hook: ToolActivityTracker
# Event: postToolUse
# Description: Track tool usage for observability
# Generated by PAI-Kiro adapter

# PAI PostToolUse hook: ToolActivityTracker
INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_name',''))" 2>/dev/null)
TOOL_RESPONSE=$(echo "$INPUT" | python3 -c "import sys,json; print(json.dumps(json.load(sys.stdin).get('tool_response',{})))" 2>/dev/null)

# Log tool activity to PAI memory
MEMORY_DIR="$HOME/.kiro/pai/MEMORY/OBSERVABILITY"
mkdir -p "$MEMORY_DIR"

echo '{"timestamp":"'"$(date -Iseconds)"'","tool":"'"$TOOL_NAME"'","success":true}' >> "$MEMORY_DIR/tool-activity.jsonl"

exit 0
