import { NextResponse } from 'next/server';
import { successResponse, errorResponse, serverErrorResponse } from '@/lib/api/response';
import { verifyR2Upload, updateUploadProgress, cleanupUploadSession } from '@/lib/upload/presigned';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth/options';
import { prisma } from '@/lib/db';
import { updateStorageUsage } from '@/lib/storage/accounts';
import { publishPhotoUploaded } from '@/lib/ably';

// Complete upload: Verify R2 upload dan save metadata
// Thumbnail akan di-generate on-demand oleh Cloudinary (auto-fetch dari R2 public URL)
export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return errorResponse('Unauthorized', 401);
    }

    const { uploadId, fileSize, width, height } = await request.json();

    if (!uploadId) {
      return errorResponse('Upload ID required', 400);
    }

    // Verifikasi upload ke R2 berhasil
    const verification = await verifyR2Upload(uploadId, fileSize, width, height);

    if (!verification.success) {
      return errorResponse(verification.error || 'Upload verification failed', 400);
    }

    const { r2Key, publicUrl, filename, galleryId, storageAccountId } = verification;

    if (!r2Key || !publicUrl || !filename || !galleryId) {
      return errorResponse('Invalid upload verification data', 400);
    }

    // Get image dimensions if not provided
    let imgWidth = width || 0;
    let imgHeight = height || 0;

    // Create photo record - NO THUMBNAIL GENERATION NEEDED
    // Cloudinary will auto-fetch from R2 public URL on-demand
    const photo = await prisma.photo.create({
      data: {
        galleryId,
        filename,
        url: publicUrl, // R2 public URL (original)
        r2Key: r2Key,
        width: imgWidth,
        height: imgHeight,
        fileSize: BigInt(fileSize),
        storageAccountId: storageAccountId || null,
        // thumbnailUrl will be generated on-the-fly by Cloudinary
      },
    });

    // Update storage usage
    if (storageAccountId) {
      await updateStorageUsage(storageAccountId, BigInt(fileSize));
    }

    // Update progress: Completed
    await updateUploadProgress(uploadId, {
      status: 'completed',
      progress: 100,
    });

    // Notify client via Ably
    await publishPhotoUploaded(galleryId, {
      photoId: photo.id,
      filename: photo.filename,
      thumbnailUrl: null, // Will be generated on-demand
    });

    // Cleanup session setelah 5 menit
    setTimeout(() => cleanupUploadSession(uploadId), 300000);

    return successResponse({
      photo: {
        id: photo.id,
        filename: photo.filename,
        url: photo.url,
        width: photo.width,
        height: photo.height,
        fileSize: photo.fileSize?.toString() || null,
        // Note: thumbnail will be generated by Cloudinary on first view
      },
    });
  } catch (error) {
    console.error('Error completing upload:', error);
    return serverErrorResponse('Failed to complete upload');
  }
}

// Get upload progress
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const uploadId = searchParams.get('uploadId');

    if (!uploadId) {
      return errorResponse('Upload ID required', 400);
    }

    const { getUploadProgress } = await import('@/lib/upload/presigned');
    const progress = await getUploadProgress(uploadId);

    if (!progress) {
      return errorResponse('Upload not found', 404);
    }

    return successResponse({ progress });
  } catch (error) {
    console.error('Error getting upload progress:', error);
    return serverErrorResponse('Failed to get upload progress');
  }
}
